# Generated by Django 4.0.4 on 2022-06-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fst_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=10)),
                ('discount', models.FloatField(max_length=10)),
                ('duration', models.CharField(max_length=50)),
                ('authorName', models.CharField(max_length=50)),
            ],
        ),
    ]
